### ISSUE TITLE
TrueColor Version?

### ISSUE THREAD

**Issue by ghost** [joedicastro/vim-molokai256#1]
Is it possible and will it make a difference to have a true color version of the molokai256 theme? Maybe copy it from sublime text 3 or something?

**Comment by joedicastro** [comment]
There is already a project that support 16-bit color and it's a molokai version for Vim

https://github.com/fmoralesc/molokayo

You can test it and see if it fits  you. I personally prefer the 256-colors version because I use vim mostly in the terminal these days and it allows me to use my config in different machines without much hustle.

**Comment by ghost** [comment]
Thanks for the info :smile:
